### ISSUE TITLE
2.1 TODO

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#180]
#This issue tracks things we need to do for 2.1 image wise.

s2i-dotnetcore:

- [x] add rpms to 2.1-dev branch (and disable CentOS build) (https://github.com/redhat-developer/s2i-dotnetcore/pull/182)
- [x] update README for 2.1 (https://github.com/redhat-developer/s2i-dotnetcore/pull/185)
- [x] merge 2.1-dev branch to master
- [x] push images
- [x] update imagestreams (https://github.com/redhat-developer/s2i-dotnetcore/pull/183)
- [x] update https://github.com/redhat-developer/s2i-dotnetcore-ex (https://github.com/redhat-developer/s2i-dotnetcore-ex/commit/1ded43a7b3737ac31e31eee352134fd7c8c0d424)
- [x] update https://github.com/redhat-developer/s2i-aspnet-musicstore-ex (https://github.com/redhat-developer/s2i-aspnet-musicstore-ex/pull/11)
- [x] update templates (incl adding DOTNET_TOOLS) (https://github.com/redhat-developer/s2i-dotnetcore/pull/184)

dotnet-jenkins-slave:

- [x] update https://github.com/redhat-developer/dotnet-jenkins-slave (https://github.com/redhat-developer/dotnet-jenkins-slave/pull/13)
- ~~[ ] update https://github.com/openshift/jenkins~~

OpenShift:
- https://github.com/openshift/library updates automatically
- [x] sync https://github.com/openshift/origin with openshift/library (https://github.com/openshift/origin/pull/21134)

Docs:
- [x] diff with 2.0: remove `DOTNET_ASPNET_STORE`; add `DOTNET_TOOLS`

CentOS:
- [x] update 2.1 CentOS dockerfiles 
- [x] update https://github.com/CentOS/container-index/blob/master/index.d/dotnet.yaml
- [x] update imagestreams_centos

CC @omajid @aslicerh @jerboaa

**Comment by ianclegg** [comment]
@tmds Tom, how long do you think it will take to work through this issue to deliver a dotnet core 2.1 image?

**Comment by tmds** [comment]
We're working on this. Currently we are validating rpms, so still some steps until we have images available. I'll try to give you an ETA after discussing with people involved.

**Comment by ianclegg** [comment]
That would great, i'm not after a hard date - just roughly how many weeks. We have a couple of projects running coreclr on Openshift which are keen to take fixes from 2.1

**Comment by tmds** [comment]
We expect images to be available in the next 3 (to 4) weeks.

FYI, Red Hat and Microsoft are working together and we want to actually release on the same day. We are not yet achieving that goal.

**Comment by ianclegg** [comment]
@tmds Many Thanks, we'll keep an eye on the repo

**Comment by azixaka** [comment]
Desperate to get 2.1 soon. It's pity there is a month delay getting the latest dotnet core version. That is a major disadvantage of OpenShift repository versus vanilla docker where things just get released on the day.

**Comment by azixaka** [comment]
@tmds Tom, how far is it from appearing in redhat catalog?

**Comment by tmds** [comment]
Images should be available in 1,5 weeks.

When we merge https://github.com/redhat-developer/s2i-dotnetcore/pull/183 they are in the catalog.

**Comment by gavrand** [comment]
Evaluating OpenShift platform for the new project. not having support for 2.1 does not help to move forward with the platform.

**Comment by tmds** [comment]
.NET Core 2.1 images are available in the catalog. https://developers.redhat.com/blog/2018/06/14/announcing-net-core-2-1-for-red-hat-platforms/

**Comment by azixaka** [comment]
Great job! Thank you very much!

**Comment by TheMidgardWatcher** [comment]
Hey guys, when we could expect CentOS based images?

**Comment by tmds** [comment]
@TheMidgardWatcher First _CentOS community_ builds rpms. Then we (s2i-dotnetcore devs) configure the CentOS container registry to build images. I'll try to get an ETA on CentOS rpms.

**Comment by tmds** [comment]
All, thank you for your patience. We do our best to release as close as possible with Microsoft. And we'll continue to work to minimize the delay.

**Comment by azixaka** [comment]
I was wondering if 2.1.1 will become available in OpenShift repository quicker as this is just a patch release? It fixes few issues which we unfortunately faced when upgraded to 2.1.

**Comment by azixaka** [comment]
@tmds Thank you.

**Comment by farshid3003** [comment]
CentOS image is not available yet. when we can use 2.1 in Origin ?

**Comment by omajid** [comment]
We are working with CentOS folks to get these built. Unfortunately, CentOS is a project run by volunteers with limited time. We can only ask them to have these bits built. We can't really influence them, or even do it ourselves as much as we want to.

**Comment by TheMidgardWatcher** [comment]
@omajid Have you got any news about CentOS images for net core 2.1/2.1.1?

**Comment by omajid** [comment]
@TheMidgardWatcher Last I heard, they said they will be looking at this after sorting RHEL 6.10 out. [That happened on Tuesday](https://blog.centos.org/2018/07/release-for-centos-linux-6-10-i386-and-x86_64/) so .NET Core 2.1 should be hitting the top of their priority list soon, I hope.

**Comment by TheMidgardWatcher** [comment]
Thank you, @omajid !

**Comment by dankmitchell** [comment]
Very much looking forward to getting on Node 8 with this release 🎉

**Comment by farshid3003** [comment]
How much it can be hart to write a very very easy docker file for centos? 
3.10 is out now but now news from centos.

**Comment by omajid** [comment]
> How much it can be hart to write a very very easy docker file for centos?

As you can probably guess, that's not to0 hard. The blocker is still having .NET Core RPMs built in CentOS so we can use them in the CentOS docker files. 

>  3.10 is out now but now news from centos.

Apologies for the delay. We are working on it.

**Comment by omajid** [comment]
.NET Core 2.1 was made available for CentOS 7 last week and containers are available at https://registry.centos.org now.

**Comment by farshid3003** [comment]
would you please edit imagestreams_centos and add 2.1 ?
Thank you so much

**Comment by aslicerh** [comment]
@farshid3003 
On it.

**Comment by aslicerh** [comment]
PR for the updated imagestream: #209

**Comment by aslicerh** [comment]
The PR for the imagestreams has been merged.
